### ISSUE TITLE
Rufo failed with exit code: 1

### ISSUE THREAD

**Issue by idoo** [jnbt/vscode-rufo#1]
Thanks for that awesome extension that fix my pain <3

It works well for whole document (when I select "Format" option in menu dropdown), but when I'm in a vim mode and select some lines of code and press `=` to format them it returns me `Rufo failed with exit code: 1`, any ideas how to fix it?

**Comment by flozada1** [comment]
Hi @idoo this probably means that you have some sort of Ruby syntax error. That is what was happening for me. Maybe you are selecting an incomplete section of code and thus contains a syntax error.

**Comment by jnbt** [comment]
@idoo I also guess it is related to some invalid Ruby code. This seems to a currently limitation of rufo, that only valid syntax can be formatted.
Even if a a whole document is valid, by selecting only a subset this might lead into invalid syntax.

Example:

```
class ApplicationController< ActionController::Base
def test
puts "foo"
end
end
```

Can be formatted via rufo, but if only the lines 2-3 are selected it doesn't work.

![Kapture 2020-10-08 at 9 20 51](https://user-images.githubusercontent.com/678542/95427306-9dd14e00-0947-11eb-8af8-dccb5886230d.gif)

**Comment by sebastianwebber** [comment]
same erorr here. how can I troubleshoot the problem?
