### ISSUE TITLE
Rufo being called incorrectly?

### ISSUE THREAD

**Issue by taylorthurlow** [jnbt/vscode-rufo#2]
Looks like the extension is trying to call Rufo like this:

~~~
rufo --filename=/path/to/file.rb -x
~~~

It exits with code 1 every time. It seems like `--filename` is for the `.rufo` config file, and not for the file to check. Shouldn't it be called like so?

~~~
rufo /path/to/file.rb -x
~~~

**Comment by smnscp** [comment]
Hi @taylorthurlow, I just encountered the same problem, looked it up in this repo and found your closed issue here. I think, you made a valid point. I’m wondering why this issue is closed. 🤔 

Here’s the [relevant code in rufo](https://github.com/ruby-formatter/rufo/blob/c1020f26d8aeb00d6c88182a9d8516443eb18cf8/lib/rufo/command.rb#L164-L166):

```ruby
      opts.on("--filename=value", "Filename to use to lookup .rufo (useful for STDIN formatting)") do |value|
        filename_for_dot_rufo = value
      end
```

The `--filename` argument is for selecting a config file.

**Comment by jnbt** [comment]
@smnscp I'm not convinced here, when I look at the code at rufo it seems that you should pass the path to the actual file, which is then used to start a search for a `.rufo` file, traversing from the path upwards.

https://github.com/ruby-formatter/rufo/blob/c1020f26d8aeb00d6c88182a9d8516443eb18cf8/lib/rufo/command.rb#L49:
```rb
result = format(code, @filename_for_dot_rufo || Dir.getwd, erb: erb)
```

and later:

```rb
def format(code, dir, erb: false)
    options = @dot_file.get_config_in(dir) || {}
```

with: 

```rb
def get_config_in(dir)
    dot_rufo = find_in(dir)
```

**Comment by smnscp** [comment]
@jnbt, you’re right. Digging deeper into Rufo’s code I now understand how the `@filename_for_dot_rufo` is actually supposed to to work. The documentation on that option is a bit confusing. On the first glimpse one is just doomed to think it’s directly referring to the `.rufo` file. But reading the code one finds that it also carries information on the code’s language (`.rb` vs `.erb`).

Anyway, sorry for bothering you. And thanks for pointing me in the right direction.

And may future misconceptors like me find this thread useful.
