### ISSUE TITLE
Couldn't find rufo for formatting (ENOENT)

### ISSUE THREAD

**Issue by lackovic** [jnbt/vscode-rufo#5]
Using Visual Studio Code `1.41.1` on Windows 10 I am getting the following error:

![2020-01-21_162642](https://user-images.githubusercontent.com/1663053/72812835-ec7c7200-3c6a-11ea-9fd8-1d649a71edfd.png)

```powershell
gem list --local | grep rufo
rufo (0.9.0)
```

**Comment by lackovic** [comment]
![2020-01-21_162642](https://user-images.githubusercontent.com/1663053/72812835-ec7c7200-3c6a-11ea-9fd8-1d649a71edfd.png)

**Comment by altjx** [comment]
Same issue here running it on Mac and using a remote SSH server. No solution?

**Comment by RenanMFernandes** [comment]
Same issue here running it on Windows 10

**Comment by rcesarvitorio** [comment]
Same issue here running it on Windows 10!!

**Comment by Drille** [comment]
Same issue here running it on Windows 10

**Comment by chwdy** [comment]
Same issue here running it on Windows 10

**Comment by rocker-bell** [comment]
same issue here, running on windows 10

**Comment by ekurkin** [comment]
try using rufo v 0.2.1
![Selection_025](https://user-images.githubusercontent.com/62241850/117173539-8b33d000-add5-11eb-84d6-3d8f971649e7.png)

**Comment by Drille** [comment]
try using rufo v 0.2.1
![Selection_025](https://user-images.githubusercontent.com/33557929/117173949-ef569400-add5-11eb-9aa7-0f371ab913ed.png)

**Comment by valbaca** [comment]
Installing the rufo plugin just change the error message to: `/bin/sh: rufo: command not found`

**Comment by Zammy** [comment]
Same issue. I have 'rufo' on global path and for some reason it cannot find 'rufo'. Windows 10. 

Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by manoharreddyporeddy** [comment]
Same issue

For now
1. installed ruby from https://rubyinstaller.org/downloads/
2. installed this vscode extension - https://marketplace.visualstudio.com/items?itemName=mbessey.vscode-rufo

Now, all working fine

**Comment by colemerrick** [comment]
I was able to resolve this issue by using the handy little suggestion by @cineron in this thread: https://github.com/bessey/vscode-rufo/issues/9

**Comment by xAt0mZ** [comment]
I had to use the following settings as @RomanTurner solution wasn't working for me

```json
"rufo.exe": "/home/xxx/.local/share/gem/ruby/3.0.0/bin/rufo",
"[ruby]": {
    "editor.defaultFormatter": "jnbt.vscode-rufo",
    "editor.formatOnSave": true
}
```

Details:
- `rufo.exe`: put here what `which rufo` gives you in a shell
- `editor.defaultFormatter`: explicitly set this extension as the default formatter for ruby, otherwise VSCode continues to tell you that you don't have a formatter installed

**Comment by CaptainOfPhB** [comment]
Check the [`README.md#Using RVM`](https://github.com/jnbt/vscode-rufo#using-rvm), if you are using RVM to install ruby, you should set `rufo.exe` path in your vscode `setting.json`.

```bash
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
$ rufo -v
rufo 0.13.0
$ whoami
my_user_name
```
Add the following configuration to your `setting.json`, then reload your vscode window. 

```json
"rufo.exe": "/Users/my_user_name/.rvm/gems/ruby-3.1.2/wrappers/rufo"
```
